### PR TITLE
EJ2-Documentation(846855)- UG documentation for Detail-template

### PR DESCRIPTION
**Pull request by Gayathri4135**
Modified the detail-template in row for both javascript and typescript

### CODE REVIEW

**Comment by Gayathri4135** [comment]
Changes reviewed in the PR: https://github.com/syncfusion-content/ej2-grid-docs/pull/38
The reviewed changes :

	1. Need to add space in "the[detailTemplate]"
	Add the extra spaces.
	2. Replace the platform name into "##Platform_Name## "
	Replaced the platform name into ##Platform_Name## .
	3. Grid data is empty on detailTemplate
	In the sample,grid data is empty on detailTemplate It can be resolved by using return function.
	4. Remove the unnecessary datasource.
	Removed the unnecessary datasource.
	5. use"e" instead of "DetailDataBoundEventArgs" in detailDataBound event's argument.
        Changed "e" instead of "DetailDataBoundEventArgs" in detailDataBound event's argument.

**Comment by Gayathri4135** [comment]
rebuild

**Comment by BalajiSGrid** [comment]
The demo and technical review have been completed.

**Comment by MaithiliyK** [comment]
Changes moved to new hotfix branch https://github.com/syncfusion-content/ej2-grid-docs/pull/129 so i closed this PR

**Pull request closed without merging**
